export class ElementMeta {
    name: string = ''
    title: string = ''
    description: string = ''
    labels: string = ''
    properties: PropertyMeta[] = []


    constructor(name: string, title: string, description: string, labels: string, properties: PropertyMeta[]) {
        this.name = name;
        this.title = title;
        this.description = description;
        this.labels = labels;
        this.properties = properties;
    }
}

export class PropertyMeta {
    name: string = ''
    kind: string = ''
    displayName: string = ''
    description: string = ''
    type: string = ''


    constructor(name: string, kind: string, displayName: string, description: string, type: string) {
        this.name = name;
        this.kind = kind;
        this.displayName = displayName;
        this.description = description;
        this.type = type;
    }
}

export class CamelMetadataApi {

    static getElementMeta = (name: string): ElementMeta | undefined => {
       return Metadata.find(value => value.name === name);
    }
}
const Metadata: ElementMeta[] = [
    new ElementMeta('policy', 'Policy', 'Defines a policy the route will use', 'null', [
        new PropertyMeta('ref', 'attribute', 'Ref', 'null', 'string'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('throwException', 'Throw Exception', 'Throws an exception', 'null', [
        new PropertyMeta('ref', 'attribute', 'Ref', 'null', 'string'),
        new PropertyMeta('message', 'attribute', 'Message', 'null', 'string'),
        new PropertyMeta('exceptionType', 'attribute', 'Exception Type', 'null', 'string'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('choice', 'Choice', 'Routes messages based on a series of predicates', 'null', [
        new PropertyMeta('whenClauses', 'element', 'When Clauses', 'null', 'array'),
        new PropertyMeta('otherwise', 'element', 'Otherwise', 'null', 'object'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('pollEnrich', 'Poll Enrich', 'Enriches messages with data polled from a secondary resource', 'null', [
        new PropertyMeta('expression', 'expression', 'Expression', 'null', 'object'),
        new PropertyMeta('timeout', 'attribute', 'Timeout', 'null', 'duration'),
        new PropertyMeta('strategyRef', 'attribute', 'Strategy Ref', 'null', 'string'),
        new PropertyMeta('strategyMethodName', 'attribute', 'Strategy Method Name', 'null', 'string'),
        new PropertyMeta('strategyMethodAllowNull', 'attribute', 'Strategy Method Allow Null', 'null', 'boolean'),
        new PropertyMeta('aggregateOnException', 'attribute', 'Aggregate On Exception', 'null', 'boolean'),
        new PropertyMeta('cacheSize', 'attribute', 'Cache Size', 'null', 'integer'),
        new PropertyMeta('ignoreInvalidEndpoint', 'attribute', 'Ignore Invalid Endpoint', 'null', 'integer'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('setBody', 'Set Body', 'Sets the contents of the message body', 'null', [
        new PropertyMeta('expression', 'expression', 'Expression', 'null', 'object'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('stop', 'Stop', 'Stops the processing of the current message', 'null', [
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('toD', 'To D', 'Sends the message to a dynamic endpoint You can specify multiple languages in the uri separated by the plus sign, such as mock:language:xpath:/order/uri where mock: would be a prefix to a xpath expression. For more dynamic behavior use Recipient List or Dynamic Router EIP instead.', 'null', [
        new PropertyMeta('uri', 'attribute', 'Uri', 'null', 'string'),
        new PropertyMeta('pattern', 'attribute', 'Pattern', 'null', 'enum'),
        new PropertyMeta('cacheSize', 'attribute', 'Cache Size', 'null', 'integer'),
        new PropertyMeta('ignoreInvalidEndpoint', 'attribute', 'Ignore Invalid Endpoint', 'null', 'boolean'),
        new PropertyMeta('allowOptimisedComponents', 'attribute', 'Allow Optimised Components', 'null', 'boolean'),
        new PropertyMeta('autoStartComponents', 'attribute', 'Auto Start Components', 'null', 'boolean'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('process', 'Process', 'Calls a Camel processor', 'null', [
        new PropertyMeta('ref', 'attribute', 'Ref', 'null', 'string'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('removeHeaders', 'Remove Headers', 'Removes message headers whose name matches a specified pattern', 'null', [
        new PropertyMeta('pattern', 'attribute', 'Pattern', 'null', 'string'),
        new PropertyMeta('excludePattern', 'attribute', 'Exclude Pattern', 'null', 'string'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('delay', 'Delay', 'Delays processing for a specified length of time', 'null', [
        new PropertyMeta('expression', 'expression', 'Expression', 'null', 'object'),
        new PropertyMeta('executorServiceRef', 'attribute', 'Executor Service Ref', 'null', 'string'),
        new PropertyMeta('asyncDelayed', 'attribute', 'Async Delayed', 'null', 'boolean'),
        new PropertyMeta('callerRunsWhenRejected', 'attribute', 'Caller Runs When Rejected', 'null', 'boolean'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('throttle', 'Throttle', 'Controls the rate at which messages are passed to the next node in the route', 'null', [
        new PropertyMeta('expression', 'expression', 'Expression', 'null', 'object'),
        new PropertyMeta('correlationExpression', 'expression', 'Correlation Expression', 'null', 'object'),
        new PropertyMeta('executorServiceRef', 'attribute', 'Executor Service Ref', 'null', 'string'),
        new PropertyMeta('timePeriodMillis', 'attribute', 'Time Period Millis', 'null', 'duration'),
        new PropertyMeta('asyncDelayed', 'attribute', 'Async Delayed', 'null', 'boolean'),
        new PropertyMeta('callerRunsWhenRejected', 'attribute', 'Caller Runs When Rejected', 'null', 'boolean'),
        new PropertyMeta('rejectExecution', 'attribute', 'Reject Execution', 'null', 'boolean'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('otherwise', 'Otherwise', 'Route to be executed when all other choices evaluate to false', 'null', [
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('removeProperty', 'Remove Property', 'Removes a named property from the message exchange', 'null', [
        new PropertyMeta('propertyName', 'attribute', 'Property Name', 'null', 'string'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('validate', 'Validate', 'Validates a message based on an expression', 'null', [
        new PropertyMeta('expression', 'expression', 'Expression', 'null', 'object'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('sort', 'Sort', 'Sorts the contents of the message', 'null', [
        new PropertyMeta('expression', 'expression', 'Expression', 'null', 'object'),
        new PropertyMeta('comparatorRef', 'attribute', 'Comparator Ref', 'null', 'string'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('from', 'From', 'Act as a message source as input to a route', 'null', [
        new PropertyMeta('uri', 'attribute', 'Uri', 'null', 'string'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('to', 'To', 'Sends the message to a static endpoint', 'null', [
        new PropertyMeta('uri', 'attribute', 'Uri', 'null', 'string'),
        new PropertyMeta('pattern', 'attribute', 'Pattern', 'null', 'enum'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('setHeader', 'Set Header', 'Sets the value of a message header', 'null', [
        new PropertyMeta('expression', 'expression', 'Expression', 'null', 'object'),
        new PropertyMeta('name', 'attribute', 'Name', 'null', 'string'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('onCompletion', 'On Completion', 'Route to be executed when normal route processing completes', 'null', [
        new PropertyMeta('mode', 'attribute', 'Mode', 'null', 'enum'),
        new PropertyMeta('onCompleteOnly', 'attribute', 'On Complete Only', 'null', 'boolean'),
        new PropertyMeta('onFailureOnly', 'attribute', 'On Failure Only', 'null', 'boolean'),
        new PropertyMeta('onWhen', 'element', 'On When', 'null', 'object'),
        new PropertyMeta('parallelProcessing', 'attribute', 'Parallel Processing', 'null', 'boolean'),
        new PropertyMeta('executorServiceRef', 'attribute', 'Executor Service Ref', 'null', 'string'),
        new PropertyMeta('useOriginalMessage', 'attribute', 'Use Original Message', 'null', 'boolean'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('removeHeader', 'Remove Header', 'Removes a named header from the message', 'null', [
        new PropertyMeta('name', 'attribute', 'Name', 'null', 'string'),
        new PropertyMeta('headerName', 'attribute', 'Header Name', 'null', 'string'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('script', 'Script', 'Executes a script from a language which does not change the message body.', 'null', [
        new PropertyMeta('expression', 'expression', 'Expression', 'null', 'object'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('enrich', 'Enrich', 'Enriches a message with data from a secondary resource', 'null', [
        new PropertyMeta('expression', 'expression', 'Expression', 'null', 'object'),
        new PropertyMeta('strategyRef', 'attribute', 'Strategy Ref', 'null', 'string'),
        new PropertyMeta('strategyMethodName', 'attribute', 'Strategy Method Name', 'null', 'string'),
        new PropertyMeta('strategyMethodAllowNull', 'attribute', 'Strategy Method Allow Null', 'null', 'string'),
        new PropertyMeta('aggregateOnException', 'attribute', 'Aggregate On Exception', 'null', 'boolean'),
        new PropertyMeta('shareUnitOfWork', 'attribute', 'Share Unit Of Work', 'null', 'boolean'),
        new PropertyMeta('cacheSize', 'attribute', 'Cache Size', 'null', 'integer'),
        new PropertyMeta('ignoreInvalidEndpoint', 'attribute', 'Ignore Invalid Endpoint', 'null', 'boolean'),
        new PropertyMeta('allowOptimisedComponents', 'attribute', 'Allow Optimised Components', 'null', 'boolean'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('log', 'Log', 'Logs the defined message to the logger', 'null', [
        new PropertyMeta('message', 'attribute', 'Message', 'null', 'string'),
        new PropertyMeta('loggingLevel', 'attribute', 'Logging Level', 'null', 'enum'),
        new PropertyMeta('logName', 'attribute', 'Log Name', 'null', 'string'),
        new PropertyMeta('marker', 'attribute', 'Marker', 'null', 'string'),
        new PropertyMeta('loggerRef', 'attribute', 'Logger Ref', 'null', 'string'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('removeProperties', 'Remove Properties', 'Removes message exchange properties whose name matches a specified pattern', 'null', [
        new PropertyMeta('pattern', 'attribute', 'Pattern', 'null', 'string'),
        new PropertyMeta('excludePattern', 'attribute', 'Exclude Pattern', 'null', 'string'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('marshal', 'Marshal', 'Marshals data into a specified format for transmission over a transport or component', 'null', [
        new PropertyMeta('dataFormatType', 'element', 'Data Format Type', 'null', 'object'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('split', 'Split', 'Splits a single message into many sub-messages.', 'null', [
        new PropertyMeta('expression', 'expression', 'Expression', 'null', 'object'),
        new PropertyMeta('delimiter', 'attribute', 'Delimiter', 'null', 'string'),
        new PropertyMeta('parallelProcessing', 'attribute', 'Parallel Processing', 'null', 'boolean'),
        new PropertyMeta('strategyRef', 'attribute', 'Strategy Ref', 'null', 'string'),
        new PropertyMeta('strategyMethodName', 'attribute', 'Strategy Method Name', 'null', 'string'),
        new PropertyMeta('strategyMethodAllowNull', 'attribute', 'Strategy Method Allow Null', 'null', 'boolean'),
        new PropertyMeta('executorServiceRef', 'attribute', 'Executor Service Ref', 'null', 'string'),
        new PropertyMeta('streaming', 'attribute', 'Streaming', 'null', 'boolean'),
        new PropertyMeta('stopOnException', 'attribute', 'Stop On Exception', 'null', 'boolean'),
        new PropertyMeta('timeout', 'attribute', 'Timeout', 'null', 'duration'),
        new PropertyMeta('onPrepareRef', 'attribute', 'On Prepare Ref', 'null', 'string'),
        new PropertyMeta('shareUnitOfWork', 'attribute', 'Share Unit Of Work', 'null', 'boolean'),
        new PropertyMeta('parallelAggregate', 'attribute', 'Parallel Aggregate', 'null', 'boolean'),
        new PropertyMeta('stopOnAggregateException', 'attribute', 'Stop On Aggregate Exception', 'null', 'boolean'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('transacted', 'Transacted', 'Enables transaction on the route', 'null', [
        new PropertyMeta('ref', 'attribute', 'Ref', 'null', 'string'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('interceptFrom', 'Intercept From', 'Intercepts incoming messages', 'null', [
        new PropertyMeta('uri', 'attribute', 'Uri', 'null', 'string'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('doCatch', 'Do Catch', 'Catches exceptions as part of a try, catch, finally block', 'null', [
        new PropertyMeta('exception', 'element', 'Exception', 'null', 'array'),
        new PropertyMeta('onWhen', 'element', 'On When', 'null', 'object'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('circuitBreaker', 'Circuit Breaker', 'null', 'null', [
        new PropertyMeta('hystrixConfiguration', 'element', 'Hystrix Configuration', 'null', 'object'),
        new PropertyMeta('resilience4jConfiguration', 'element', 'Resilience4j Configuration', 'null', 'object'),
        new PropertyMeta('faultToleranceConfiguration', 'element', 'Fault Tolerance Configuration', 'null', 'object'),
        new PropertyMeta('configurationRef', 'attribute', 'Configuration Ref', 'null', 'string'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('convertBodyTo', 'Convert Body To', 'Converts the message body to another type', 'null', [
        new PropertyMeta('type', 'attribute', 'Type', 'null', 'string'),
        new PropertyMeta('charset', 'attribute', 'Charset', 'null', 'string'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('intercept', 'Intercept', 'Intercepts a message at each step in the route', 'null', [
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('unmarshal', 'Unmarshal', 'Converts the message data received from the wire into a format that Apache Camel processors can consume', 'null', [
        new PropertyMeta('dataFormatType', 'element', 'Data Format Type', 'null', 'object'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('onFallback', 'On Fallback', 'Route to be executed when Hystrix EIP executes fallback', 'null', [
        new PropertyMeta('fallbackViaNetwork', 'attribute', 'Fallback Via Network', 'null', 'boolean'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('setExchangePattern', 'Set Exchange Pattern', 'Sets the exchange pattern on the message exchange', 'null', [
        new PropertyMeta('pattern', 'attribute', 'Pattern', 'null', 'enum'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('recipientList', 'Recipient List', 'Routes messages to a number of dynamically specified recipients (dynamic to)', 'null', [
        new PropertyMeta('expression', 'expression', 'Expression', 'null', 'object'),
        new PropertyMeta('delimiter', 'attribute', 'Delimiter', 'null', 'string'),
        new PropertyMeta('parallelProcessing', 'attribute', 'Parallel Processing', 'null', 'boolean'),
        new PropertyMeta('strategyRef', 'attribute', 'Strategy Ref', 'null', 'string'),
        new PropertyMeta('strategyMethodName', 'attribute', 'Strategy Method Name', 'null', 'string'),
        new PropertyMeta('strategyMethodAllowNull', 'attribute', 'Strategy Method Allow Null', 'null', 'boolean'),
        new PropertyMeta('executorServiceRef', 'attribute', 'Executor Service Ref', 'null', 'string'),
        new PropertyMeta('stopOnException', 'attribute', 'Stop On Exception', 'null', 'boolean'),
        new PropertyMeta('ignoreInvalidEndpoints', 'attribute', 'Ignore Invalid Endpoints', 'null', 'boolean'),
        new PropertyMeta('streaming', 'attribute', 'Streaming', 'null', 'boolean'),
        new PropertyMeta('timeout', 'attribute', 'Timeout', 'null', 'duration'),
        new PropertyMeta('onPrepareRef', 'attribute', 'On Prepare Ref', 'null', 'string'),
        new PropertyMeta('shareUnitOfWork', 'attribute', 'Share Unit Of Work', 'null', 'boolean'),
        new PropertyMeta('cacheSize', 'attribute', 'Cache Size', 'null', 'integer'),
        new PropertyMeta('parallelAggregate', 'attribute', 'Parallel Aggregate', 'null', 'boolean'),
        new PropertyMeta('stopOnAggregateException', 'attribute', 'Stop On Aggregate Exception', 'null', 'boolean'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('bean', 'Bean', 'Calls a Java bean', 'null', [
        new PropertyMeta('ref', 'attribute', 'Ref', 'null', 'string'),
        new PropertyMeta('method', 'attribute', 'Method', 'null', 'string'),
        new PropertyMeta('beanType', 'attribute', 'Bean Type', 'null', 'string'),
        new PropertyMeta('cache', 'attribute', 'Cache', 'null', 'boolean'),
        new PropertyMeta('scope', 'attribute', 'Scope', 'null', 'enum'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('multicast', 'Multicast', 'Routes the same message to multiple paths either sequentially or in parallel.', 'null', [
        new PropertyMeta('parallelProcessing', 'attribute', 'Parallel Processing', 'null', 'boolean'),
        new PropertyMeta('strategyRef', 'attribute', 'Strategy Ref', 'null', 'string'),
        new PropertyMeta('strategyMethodName', 'attribute', 'Strategy Method Name', 'null', 'string'),
        new PropertyMeta('strategyMethodAllowNull', 'attribute', 'Strategy Method Allow Null', 'null', 'boolean'),
        new PropertyMeta('executorServiceRef', 'attribute', 'Executor Service Ref', 'null', 'string'),
        new PropertyMeta('streaming', 'attribute', 'Streaming', 'null', 'boolean'),
        new PropertyMeta('stopOnException', 'attribute', 'Stop On Exception', 'null', 'boolean'),
        new PropertyMeta('timeout', 'attribute', 'Timeout', 'null', 'duration'),
        new PropertyMeta('onPrepareRef', 'attribute', 'On Prepare Ref', 'null', 'string'),
        new PropertyMeta('shareUnitOfWork', 'attribute', 'Share Unit Of Work', 'null', 'boolean'),
        new PropertyMeta('parallelAggregate', 'attribute', 'Parallel Aggregate', 'null', 'boolean'),
        new PropertyMeta('stopOnAggregateException', 'attribute', 'Stop On Aggregate Exception', 'null', 'boolean'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('inOnly', 'In Only', 'Marks the exchange pattern for the route to one way', 'null', [
        new PropertyMeta('uri', 'attribute', 'Uri', 'null', 'string'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('loadBalance', 'Load Balance', 'Balances message processing among a number of nodes', 'null', [
        new PropertyMeta('loadBalancerType', 'element', 'Load Balancer Type', 'null', 'object'),
        new PropertyMeta('inheritErrorHandler', 'attribute', 'Inherit Error Handler', 'null', 'boolean'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('routingSlip', 'Routing Slip', 'Routes a message through a series of steps that are pre-determined (the slip)', 'null', [
        new PropertyMeta('expression', 'expression', 'Expression', 'null', 'object'),
        new PropertyMeta('uriDelimiter', 'attribute', 'Uri Delimiter', 'null', 'string'),
        new PropertyMeta('ignoreInvalidEndpoints', 'attribute', 'Ignore Invalid Endpoints', 'null', 'boolean'),
        new PropertyMeta('cacheSize', 'attribute', 'Cache Size', 'null', 'integer'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('rollback', 'Rollback', 'Forces a rollback by stopping routing the message', 'null', [
        new PropertyMeta('markRollbackOnly', 'attribute', 'Mark Rollback Only', 'null', 'boolean'),
        new PropertyMeta('markRollbackOnlyLast', 'attribute', 'Mark Rollback Only Last', 'null', 'boolean'),
        new PropertyMeta('message', 'attribute', 'Message', 'null', 'string'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('whenSkipSendToEndpoint', 'When Skip Send To Endpoint', 'Predicate to determine if the message should be sent or not to the endpoint, when using interceptSentToEndpoint.', 'null', [
        new PropertyMeta('expression', 'expression', 'Expression', 'null', 'object'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('wireTap', 'Wire Tap', 'Routes a copy of a message (or creates a new message) to a secondary destination while continue routing the original message.', 'null', [
        new PropertyMeta('processorRef', 'attribute', 'Processor Ref', 'null', 'string'),
        new PropertyMeta('body', 'expression', 'Body', 'null', 'object'),
        new PropertyMeta('executorServiceRef', 'attribute', 'Executor Service Ref', 'null', 'string'),
        new PropertyMeta('copy', 'attribute', 'Copy', 'null', 'boolean'),
        new PropertyMeta('dynamicUri', 'attribute', 'Dynamic Uri', 'null', 'boolean'),
        new PropertyMeta('onPrepareRef', 'attribute', 'On Prepare Ref', 'null', 'string'),
        new PropertyMeta('uri', 'attribute', 'Uri', 'null', 'string'),
        new PropertyMeta('pattern', 'attribute', 'Pattern', 'null', 'enum'),
        new PropertyMeta('cacheSize', 'attribute', 'Cache Size', 'null', 'integer'),
        new PropertyMeta('ignoreInvalidEndpoint', 'attribute', 'Ignore Invalid Endpoint', 'null', 'boolean'),
        new PropertyMeta('allowOptimisedComponents', 'attribute', 'Allow Optimised Components', 'null', 'boolean'),
        new PropertyMeta('autoStartComponents', 'attribute', 'Auto Start Components', 'null', 'boolean'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('loop', 'Loop', 'Processes a message multiple times', 'null', [
        new PropertyMeta('expression', 'expression', 'Expression', 'null', 'object'),
        new PropertyMeta('copy', 'attribute', 'Copy', 'null', 'boolean'),
        new PropertyMeta('doWhile', 'attribute', 'Do While', 'null', 'boolean'),
        new PropertyMeta('breakOnShutdown', 'attribute', 'Break On Shutdown', 'null', 'boolean'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('interceptSendToEndpoint', 'Intercept Send To Endpoint', 'Intercepts messages being sent to an endpoint', 'null', [
        new PropertyMeta('uri', 'attribute', 'Uri', 'null', 'string'),
        new PropertyMeta('skipSendToOriginalEndpoint', 'attribute', 'Skip Send To Original Endpoint', 'null', 'string'),
        new PropertyMeta('afterUri', 'attribute', 'After Uri', 'null', 'string'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('doTry', 'Do Try', 'Marks the beginning of a try, catch, finally block', 'null', [
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('resequence', 'Resequence', 'Resequences (re-order) messages based on an expression', 'null', [
        new PropertyMeta('expression', 'expression', 'Expression', 'null', 'object'),
        new PropertyMeta('resequencerConfig', 'element', 'Resequencer Config', 'null', 'object'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('expression', 'Expression', 'A useful base class for an expression', 'null', [
        new PropertyMeta('expression', 'value', 'Expression', 'null', 'string'),
        new PropertyMeta('trim', 'attribute', 'Trim', 'null', 'boolean'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
    ]),
    new ElementMeta('serviceCall', 'Service Call', 'To call remote services', 'null', [
        new PropertyMeta('expression', 'element', 'Expression', 'null', 'object'),
        new PropertyMeta('name', 'attribute', 'Name', 'null', 'string'),
        new PropertyMeta('uri', 'attribute', 'Uri', 'null', 'string'),
        new PropertyMeta('component', 'attribute', 'Component', 'null', 'string'),
        new PropertyMeta('pattern', 'attribute', 'Pattern', 'null', 'enum'),
        new PropertyMeta('configurationRef', 'attribute', 'Configuration Ref', 'null', 'string'),
        new PropertyMeta('serviceDiscoveryRef', 'attribute', 'Service Discovery Ref', 'null', 'string'),
        new PropertyMeta('serviceFilterRef', 'attribute', 'Service Filter Ref', 'null', 'string'),
        new PropertyMeta('serviceChooserRef', 'attribute', 'Service Chooser Ref', 'null', 'string'),
        new PropertyMeta('loadBalancerRef', 'attribute', 'Load Balancer Ref', 'null', 'string'),
        new PropertyMeta('expressionRef', 'attribute', 'Expression Ref', 'null', 'string'),
        new PropertyMeta('serviceDiscoveryConfiguration', 'element', 'Service Discovery Configuration', 'null', 'object'),
        new PropertyMeta('serviceFilterConfiguration', 'element', 'Service Filter Configuration', 'null', 'object'),
        new PropertyMeta('loadBalancerConfiguration', 'element', 'Load Balancer Configuration', 'null', 'object'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('sample', 'Sample', 'Extract a sample of the messages passing through a route', 'null', [
        new PropertyMeta('samplePeriod', 'attribute', 'Sample Period', 'null', 'duration'),
        new PropertyMeta('messageFrequency', 'attribute', 'Message Frequency', 'null', 'integer'),
        new PropertyMeta('units', 'attribute', 'Units', 'null', 'enum'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('dynamicRouter', 'Dynamic Router', 'Routes messages based on dynamic rules', 'null', [
        new PropertyMeta('expression', 'expression', 'Expression', 'null', 'object'),
        new PropertyMeta('uriDelimiter', 'attribute', 'Uri Delimiter', 'null', 'string'),
        new PropertyMeta('ignoreInvalidEndpoints', 'attribute', 'Ignore Invalid Endpoints', 'null', 'string'),
        new PropertyMeta('cacheSize', 'attribute', 'Cache Size', 'null', 'integer'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('pipeline', 'Pipeline', 'Routes the message to a sequence of processors.', 'null', [
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('saga', 'Saga', 'Enables sagas on the route', 'null', [
        new PropertyMeta('propagation', 'attribute', 'Propagation', 'null', 'enum'),
        new PropertyMeta('completionMode', 'attribute', 'Completion Mode', 'null', 'enum'),
        new PropertyMeta('timeoutInMilliseconds', 'attribute', 'Timeout In Milliseconds', 'null', 'integer'),
        new PropertyMeta('timeout', 'attribute', 'Timeout', 'null', 'duration'),
        new PropertyMeta('compensation', 'element', 'Compensation', 'null', 'object'),
        new PropertyMeta('completion', 'element', 'Completion', 'null', 'object'),
        new PropertyMeta('option', 'element', 'Option', 'null', 'array'),
        new PropertyMeta('sagaServiceRef', 'attribute', 'Saga Service Ref', 'null', 'string'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('threads', 'Threads', 'Specifies that all steps after this node are processed asynchronously', 'null', [
        new PropertyMeta('executorServiceRef', 'attribute', 'Executor Service Ref', 'null', 'string'),
        new PropertyMeta('poolSize', 'attribute', 'Pool Size', 'null', 'integer'),
        new PropertyMeta('maxPoolSize', 'attribute', 'Max Pool Size', 'null', 'integer'),
        new PropertyMeta('keepAliveTime', 'attribute', 'Keep Alive Time', 'null', 'integer'),
        new PropertyMeta('timeUnit', 'attribute', 'Time Unit', 'null', 'enum'),
        new PropertyMeta('maxQueueSize', 'attribute', 'Max Queue Size', 'null', 'integer'),
        new PropertyMeta('allowCoreThreadTimeOut', 'attribute', 'Allow Core Thread Time Out', 'null', 'boolean'),
        new PropertyMeta('threadName', 'attribute', 'Thread Name', 'null', 'string'),
        new PropertyMeta('rejectedPolicy', 'attribute', 'Rejected Policy', 'null', 'enum'),
        new PropertyMeta('callerRunsWhenRejected', 'attribute', 'Caller Runs When Rejected', 'null', 'string'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('when', 'When', 'Triggers a route when an expression evaluates to true', 'null', [
        new PropertyMeta('expression', 'expression', 'Expression', 'null', 'object'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('claimCheck', 'Claim Check', 'The Claim Check EIP allows you to replace message content with a claim check (a unique key), which can be used to retrieve the message content at a later time.', 'null', [
        new PropertyMeta('operation', 'attribute', 'Operation', 'null', 'enum'),
        new PropertyMeta('key', 'attribute', 'Key', 'null', 'string'),
        new PropertyMeta('filter', 'attribute', 'Filter', 'null', 'string'),
        new PropertyMeta('strategyRef', 'attribute', 'Strategy Ref', 'null', 'string'),
        new PropertyMeta('strategyMethodName', 'attribute', 'Strategy Method Name', 'null', 'string'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('doFinally', 'Do Finally', 'Path traversed when a try, catch, finally block exits', 'null', [
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('filter', 'Filter', 'Filter out messages based using a predicate', 'null', [
        new PropertyMeta('expression', 'expression', 'Expression', 'null', 'object'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('aggregate', 'Aggregate', 'Aggregates many messages into a single message', 'null', [
        new PropertyMeta('correlationExpression', 'expression', 'Correlation Expression', 'null', 'object'),
        new PropertyMeta('completionPredicate', 'expression', 'Completion Predicate', 'null', 'object'),
        new PropertyMeta('completionTimeoutExpression', 'expression', 'Completion Timeout Expression', 'null', 'object'),
        new PropertyMeta('completionSizeExpression', 'expression', 'Completion Size Expression', 'null', 'object'),
        new PropertyMeta('optimisticLockRetryPolicy', 'element', 'Optimistic Lock Retry Policy', 'null', 'object'),
        new PropertyMeta('parallelProcessing', 'attribute', 'Parallel Processing', 'null', 'boolean'),
        new PropertyMeta('optimisticLocking', 'attribute', 'Optimistic Locking', 'null', 'boolean'),
        new PropertyMeta('executorServiceRef', 'attribute', 'Executor Service Ref', 'null', 'string'),
        new PropertyMeta('timeoutCheckerExecutorServiceRef', 'attribute', 'Timeout Checker Executor Service Ref', 'null', 'string'),
        new PropertyMeta('aggregationRepositoryRef', 'attribute', 'Aggregation Repository Ref', 'null', 'string'),
        new PropertyMeta('strategyRef', 'attribute', 'Strategy Ref', 'null', 'string'),
        new PropertyMeta('strategyMethodName', 'attribute', 'Strategy Method Name', 'null', 'string'),
        new PropertyMeta('strategyMethodAllowNull', 'attribute', 'Strategy Method Allow Null', 'null', 'boolean'),
        new PropertyMeta('completionSize', 'attribute', 'Completion Size', 'null', 'integer'),
        new PropertyMeta('completionInterval', 'attribute', 'Completion Interval', 'null', 'duration'),
        new PropertyMeta('completionTimeout', 'attribute', 'Completion Timeout', 'null', 'duration'),
        new PropertyMeta('completionTimeoutCheckerInterval', 'attribute', 'Completion Timeout Checker Interval', 'null', 'duration'),
        new PropertyMeta('completionFromBatchConsumer', 'attribute', 'Completion From Batch Consumer', 'null', 'boolean'),
        new PropertyMeta('completionOnNewCorrelationGroup', 'attribute', 'Completion On New Correlation Group', 'null', 'boolean'),
        new PropertyMeta('eagerCheckCompletion', 'attribute', 'Eager Check Completion', 'null', 'boolean'),
        new PropertyMeta('ignoreInvalidCorrelationKeys', 'attribute', 'Ignore Invalid Correlation Keys', 'null', 'boolean'),
        new PropertyMeta('closeCorrelationKeyOnCompletion', 'attribute', 'Close Correlation Key On Completion', 'null', 'integer'),
        new PropertyMeta('discardOnCompletionTimeout', 'attribute', 'Discard On Completion Timeout', 'null', 'boolean'),
        new PropertyMeta('discardOnAggregationFailure', 'attribute', 'Discard On Aggregation Failure', 'null', 'boolean'),
        new PropertyMeta('forceCompletionOnStop', 'attribute', 'Force Completion On Stop', 'null', 'boolean'),
        new PropertyMeta('completeAllOnStop', 'attribute', 'Complete All On Stop', 'null', 'boolean'),
        new PropertyMeta('aggregateControllerRef', 'attribute', 'Aggregate Controller Ref', 'null', 'string'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('transform', 'Transform', 'Transforms the message body based on an expression', 'null', [
        new PropertyMeta('expression', 'expression', 'Expression', 'null', 'object'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('idempotentConsumer', 'Idempotent Consumer', 'Filters out duplicate messages', 'null', [
        new PropertyMeta('expression', 'expression', 'Expression', 'null', 'object'),
        new PropertyMeta('messageIdRepositoryRef', 'attribute', 'Message Id Repository Ref', 'null', 'string'),
        new PropertyMeta('eager', 'attribute', 'Eager', 'null', 'boolean'),
        new PropertyMeta('completionEager', 'attribute', 'Completion Eager', 'null', 'string'),
        new PropertyMeta('skipDuplicate', 'attribute', 'Skip Duplicate', 'null', 'boolean'),
        new PropertyMeta('removeOnFailure', 'attribute', 'Remove On Failure', 'null', 'boolean'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('setProperty', 'Set Property', 'Sets a named property on the message exchange', 'null', [
        new PropertyMeta('expression', 'expression', 'Expression', 'null', 'object'),
        new PropertyMeta('name', 'attribute', 'Name', 'null', 'string'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
    new ElementMeta('inOut', 'In Out', 'Marks the exchange pattern for the route to request/reply', 'null', [
        new PropertyMeta('uri', 'attribute', 'Uri', 'null', 'string'),
        new PropertyMeta('id', 'attribute', 'Id', 'null', 'string'),
        new PropertyMeta('description', 'element', 'Description', 'null', 'object'),
    ]),
]
