apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: karavan
    openshift.io/display-name: karavan
  name: karavan
spec:
  finalizers:
    - kubernetes

---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: karavan-flows
    openshift.io/display-name: karavan-flows
  name: karavan-flows
spec:
  finalizers:
    - kubernetes